export const us_data = [
  "Alaska",
  "Hawaii",
  "Alabama",
  "Arkansas",
  "Arizona",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Iowa",
  "Idaho",
  "Illinois",
  "Indiana",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Massachusetts",
  "Maryland",
  "Maine",
  "Michigan",
  "Minnesota",
  "Missouri",
  "Mississippi",
  "Montana",
  "North Carolina",
  "North Dakota",
  "Nebraska",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "Nevada",
  "New York",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Virginia",
  "Vermont",
  "Washington",
  "Wisconsin",
  "West Virginia",
  "Wyoming",
]

export const africa_data = [
  "Tanzania",
  "Western Sahara",
  "Democratic Republic of the Congo",
  "Somalia",
  "Kenya",
  "Sudan",
  "Chad",
  "South Africa",
  "Lesotho",
  "Zimbabwe",
  "Botswana",
  "Namibia",
  "Senegal",
  "Mali",
  "Mauritania",
  "Benin",
  "Niger",
  "Nigeria",
  "Cameroon",
  "Togo",
  "Ghana",
  "Côte d'Ivoire",
  "Guinea",
  "Guinea-Bissau",
  "Liberia",
  "Sierra Leone",
  "Burkina Faso",
  "Central African Republic",
  "Republic of the Congo",
  "Gabon",
  "Equatorial Guinea",
  "Zambia",
  "Malawi",
  "Mozambique",
  "eSwatini",
  "Angola",
  "Burundi",
  "Madagascar",
  "The Gambia",
  "Tunisia",
  "Algeria",
  "Eritrea",
  "Morocco",
  "Egypt",
  "Libya",
  "Ethiopia",
  "Djibouti",
  "Somaliland",
  "Uganda",
  "Rwanda",
  "South Sudan",
]

export const asia_data = [
  "Kazakhstan",
  "Uzbekistan",
  "Indonesia",
  "Russian Federation",
  "Timor-Leste",
  "Israel",
  "Lebanon",
  "Palestine",
  "Jordan",
  "United Arab Emirates",
  "Qatar",
  "Kuwait",
  "Iraq",
  "Oman",
  "Cambodia",
  "Thailand",
  "Lao PDR",
  "Myanmar",
  "Vietnam",
  "Dem. Rep. Korea",
  "Republic of Korea",
  "Mongolia",
  "India",
  "Bangladesh",
  "Bhutan",
  "Nepal",
  "Pakistan",
  "Afghanistan",
  "Tajikistan",
  "Kyrgyzstan",
  "Turkmenistan",
  "Iran",
  "Syria",
  "Armenia",
  "Turkey",
  "Sri Lanka",
  "China",
  "Taiwan",
  "Azerbaijan",
  "Georgia",
  "Philippines",
  "Malaysia",
  "Brunei Darussalam",
  "Japan",
  "Yemen",
  "Saudi Arabia",
  "Northern Cyprus",
  "Cyprus",
]

export const europe_data = [
  "Russian Federation",
  "Norway",
  "France",
  "Sweden",
  "Belarus",
  "Ukraine",
  "Poland",
  "Austria",
  "Hungary",
  "Moldova",
  "Romania",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Germany",
  "Bulgaria",
  "Greece",
  "Albania",
  "Croatia",
  "Switzerland",
  "Luxembourg",
  "Belgium",
  "Netherlands",
  "Portugal",
  "Spain",
  "Ireland",
  "Italy",
  "Denmark",
  "United Kingdom",
  "Iceland",
  "Slovenia",
  "Finland",
  "Slovakia",
  "Czech Republic",
  "Bosnia and Herzegovina",
  "Macedonia",
  "Serbia",
  "Montenegro",
  "Kosovo",
]

export const na_data = [
  "Canada",
  "Haiti",
  "Dominican Rep.",
  "Bahamas",
  "Greenland",
  "Mexico",
  "Panama",
  "Costa Rica",
  "Nicaragua",
  "Honduras",
  "El Salvador",
  "Guatemala",
  "Belize",
  "Puerto Rico",
  "Jamaica",
  "Cuba",
  "Trinidad and Tobago",
  "United States of America",
]

export const sa_data = [
  "Argentina",
  "Chile",
  "Falkland Islands",
  "Uruguay",
  "Brazil",
  "Bolivia",
  "Peru",
  "Colombia",
  "Venezuela",
  "Guyana",
  "Suriname",
  "French Guiana",
  "Ecuador",
  "Paraguay",
]
